#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

extends: default

rules:
  line-length:
    max: 150
    level: warning
  truthy:
    level: error
    allowed-values: ["false", "true", "on"]  # On to enable the on: setup for GitHub actions.
  document-start: disable
