#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

title: "Challenges and Help"
labels: ["Challenges and Help"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share any questions or challenges you have with a Stanford Biodesign Digital Health Group-related project!
  - type: dropdown
    attributes:
      label: What Stanford Biodesign Digital Health Group-related project challenge related to?
      description: Use the Stanford Spezi GitHub Discussions page to discuss any Spezi-related challenges.
      options:
        - LLMonFHIR
        - HealthGPT
        - Phoenix
        - HealthKitOnFHIR
        - ResearchKitOnFHIR
        - XCTRuntimeAssertions
        - XCTHealthKit
        - XCTestExtensions
        - ImageSource
        - action-swiftlint
        - ContinousIntegration
        - SwiftPackageTemplate
        - TemplateApplication
        - Other project
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: | 
        Please provide a description of how to reproduce the problem you are facing.
        
        If you are facing a problem in your application, please provide a link to a failing UI test or unit test to reproduce the issue.
        If you face a build error or a problem with releasing your application, please link a GitHub Action run reproducing the error outside of your development.
      placeholder: | 
        What steps did you follow to get the problem?
        Provide links and steps on how to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: expectedbehavior
    attributes:
      label: Expected behavior
      description: Please provide a clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additionalcontext
    attributes:
      label: Additional context
      description:  |
        Please provide any additional context that might be relevant to your setup problem.
      placeholder: Any additional context that might be relevant to your problem.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this projects's Code of Conduct and Contributing Guidelines
          required: true
