#
# This source file is part of the Stanford Biodesign for Digital Health open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

title: "[Show and Tell] "
labels: ["Show and Tell"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your project using our software and your enthusiasm for digital health!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your project and the software you have developed!
        Share your background, motivation for your project, and additional scientific background.
        
        Feel free to share screenshots, videos, and examples demonstrating your project.
      placeholder: A descriptive overview of your project, including images, videos, and examples.
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Contact Information and Additional Context
      description: | 
        Feel free to share some contact information and additional links to your project!
      placeholder: | 
        Your contact information and additional context.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this projects's Code of Conduct and Contributing Guidelines
          required: true
