#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Check README Links

on:
    workflow_call:

jobs:
    check_markdown_links:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: gaurav-nelson/github-action-markdown-link-check@v1