#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releasetag:
    name: Tag Release
    uses: ./.github/workflows/action-release-tag.yml
    permissions:
      contents: write
    with:
      user: PaulsAutomationBot
