#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Static Analysis

on:
  workflow_call:
    inputs:
      library_products:
        type: string
        required: true
      platform_name:
        type: string
        required: true
      platform_version:
        type: string
        default: ""
      diagnose_breaking_changes:
        type: boolean
        default: true

permissions:
  contents: read
  pull-requests: write

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  markdown_link_check:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
  breaking_changes:
    name: Diagnose Breaking Changes
    uses: ./.github/workflows/swift-package-breaking-changes.yml
    if: ${{ inputs.diagnose_breaking_changes && github.ref_name != 'main' }}
    with:
      library_products: ${{ inputs.library_products }}
      platform_name: ${{ inputs.platform_name }}
      platform_version: ${{ inputs.platform_version }}
      runsonlabels: '["macOS", "self-hosted"]'
