#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: ./.github/workflows/reuse.yml
  markdown_link_check:
    name: Markdown Link Check
    uses: ./.github/workflows/markdown-link-check.yml
  yamllint:
    name: YAML Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint with custom config
        run: yamllint -c .yamllint.yml .
